<h3><b>Get Microbiom Data

In [8]:
import pandas as pd
import numpy as np

In [9]:
original_micr_data = pd.read_excel('microbiom_data.xlsx')

In [10]:
type_constrained_micr_data = pd.concat([original_micr_data.iloc[0:413,0].astype('string'),
                                        original_micr_data.iloc[0:413,1:].astype('float')], axis=1)

In [11]:
numerical_micr_data = type_constrained_micr_data.copy()
sample = numerical_micr_data.pop('Sample')
visit = numerical_micr_data.pop('Visit')

In [12]:
N = sample.apply(lambda row: float(row[0:3]))
N.name = 'N'

In [13]:
na_micr_sum = (numerical_micr_data == 0).sum()
selected_otu = na_micr_sum[na_micr_sum<(numerical_micr_data.shape[0]*0.5)].index
otu = numerical_micr_data.loc[:, selected_otu]

In [14]:
micr_data = pd.concat([N, visit, otu], axis=1)
micr_data.set_index('N', inplace=True)

In [15]:
micr_data

,Visit,OTU_1,OTU_2,OTU_3,OTU_4,OTU_5,OTU_6,OTU_7,OTU_8,OTU_10,...,OTU_123,OTU_128,OTU_132,OTU_135,OTU_139,OTU_143,OTU_152,OTU_159,OTU_166,OTU_257
N,,,,,,,,,,,,,,,,,,,,,
281.0,99.0,355.0,5.0,76.0,0.0,183.0,59.0,112.0,82.0,121.0,...,37.0,6.0,5.0,0.0,0.0,95.0,24.0,52.0,66.0,14.0
288.0,99.0,213.0,132.0,123.0,993.0,71.0,0.0,101.0,46.0,387.0,...,11.0,4.0,21.0,23.0,0.0,94.0,7.0,31.0,95.0,14.0
289.0,99.0,0.0,0.0,410.0,0.0,143.0,99.0,111.0,30.0,114.0,...,14.0,0.0,6.0,150.0,5.0,6.0,60.0,5.0,0.0,47.0
290.0,99.0,2280.0,192.0,68.0,920.0,141.0,1250.0,466.0,141.0,522.0,...,18.0,88.0,35.0,0.0,16.0,24.0,0.0,0.0,54.0,35.0
291.0,99.0,1348.0,158.0,319.0,0.0,455.0,0.0,634.0,57.0,3021.0,...,6.0,40.0,25.0,0.0,0.0,0.0,20.0,56.0,37.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872.0,146.0,0.0,1362.0,898.0,229.0,1027.0,1177.0,322.0,1881.0,16.0,...,0.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
873.0,146.0,445.0,643.0,1059.0,0.0,2040.0,777.0,1471.0,432.0,0.0,...,52.0,48.0,52.0,0.0,8.0,0.0,13.0,0.0,0.0,0.0
874.0,146.0,1652.0,28.0,1158.0,0.0,488.0,0.0,44.0,271.0,0.0,...,22.0,21.0,48.0,64.0,8.0,0.0,13.0,0.0,0.0,0.0
875.0,146.0,5857.0,953.0,559.0,0.0,1206.0,2907.0,304.0,1033.0,19.0,...,7.0,63.0,36.0,0.0,0.0,7.0,16.0,0.0,0.0,0.0
881.0,146.0,4.0,838.0,4028.0,13.0,2265.0,37.0,2864.0,2338.0,392.0,...,16.0,23.0,26.0,0.0,0.0,12.0,424.0,0.0,0.0,73.0

<h3><b>Get Clinical Data

In [86]:
original_clinical_data = pd.read_excel('clinical_data.xlsx')
clinical_param = [
                    'N', 'срок_берем1', 'диета_до_1визита', 'диета_срок', 'Глюкоза_нт_общая','через1час_тест', 'через2часа_тест',
                    'прибавка_m1','отеки1', 'АД_сист1', 'АД_диаст1', 'N_беременностей', 'N_родов', 'N_невынашивание','N_абортов',
                    'menses', 'АГ', 'НТГ', 'гсд_анамнез', 'СПКЯ', 'СД_у_родственников', 'пролактин', 'КОК', 'курение_до_беременности', 
                    'курение_во_время', 'возраст', 'рост', 'вес_до_берем','ИМТ', 'фрукты1', 'пирожные1', 'выпечка1', 'шоколад1',
                    'молочное_обезжир1', 'молочное_необезжир1', 'бобовые1', 'мясо1', 'сухофрукты1', 'рыба1', 'хлеб_цельное1', 'хлеб_любой1',
                    'соусы1', 'овощи1', 'овощи1_сырые', 'алкоголь1', 'сладкие_напитки1', 'кофе1', 'сосиски1', 'фрукты2', 'пирожные2',
                    'выпечка2', 'шоколад2', 'молочное_обезжир2', 'молочное_необезжир2', 'бобовые2', 'мясо2', 'сухофрукы2', 'рыба2',
                    'хлеб_цельнозерновой_2', 'хлеб_любой2', 'соусы2', 'овощи2', 'овощи2_сырые', 'алкоголь2', 'сладкие_напитки2', 'кофе2',
                    'сосиски2', 'ходьба1', 'подъем1', 'спорт1', 'ходьба2', 'подъем2', 'спорт2', 'глю_нт_V1', 'кетоны_V1', 'HbA1C_V1',
                    'инсулин_V1', 'лептин_V1', 'ФР_V1', 'БОМК_визит1', 'Хол_V1', 'ТГ_V1', 'ЛПВП_V1', 'ЛПОНП_V1', 'ЛПНП_V1', 'КА_V1',
                    'АБ_бер_ть', 'АБ_до_cgms1', 'АБ_срок', 'quality_cgm1'
                ]
clinical_data = original_clinical_data.loc[(original_clinical_data['quality_cgm1']==0) | (original_clinical_data['quality_cgm1']==5), clinical_param]
clinical_data.drop(columns=['quality_cgm1'], axis=1, inplace=True)
clinical_data['диета_срок'] = clinical_data['диета_срок'].astype('float')

In [87]:
cat_params = clinical_data.select_dtypes('category').columns
na_cat = clinical_data[cat_params].isna().sum()>0
clinical_data[na_cat.index.tolist()] = clinical_data[na_cat.index.tolist()].apply(lambda x: x.cat.add_categories('нет информации'))
clinical_data[na_cat.index.tolist()] = clinical_data[na_cat.index.tolist()].fillna('нет информации')

In [88]:
clinical_data[cat_params] = clinical_data[cat_params].apply(lambda x: x.astype('str'))
clinical_data[cat_params] = clinical_data[cat_params].apply(lambda x: x.astype('category'))

<h3><b>Get monitoring Data

In [89]:
original_monitoring_data = pd.read_excel('monitoring_data.xlsx', sheet_name='Formatted')
monitoring_data = original_monitoring_data.astype('float')

<h3><b>Conjugate tables

In [90]:
data = clinical_data.merge(micr_data, on='N', how='inner')

In [91]:
data = monitoring_data.merge(data, on='N', how='inner')

In [92]:
data.drop(columns=['CGM_mean','CGM_above','CGM_below','CGM_range','BGb60_to_mean'], axis=1, inplace=True)

In [93]:
data.dropna(subset=['BG60','BG120','BGMax','AUC60','AUC120','iAUC60','iAUC120'], inplace=True)

In [94]:
data = data.loc[(data['Visit']==99) | (data['Visit']==146), :]

In [95]:
data.to_excel('data_for_training_0.xlsx', index=False)

In [96]:
data.to_pickle('data_for_training_0.pkl')

In [97]:
data.drop(columns=otu, inplace=True)

In [98]:
data.to_excel('data_for_training_1.xlsx', index=False)

In [99]:
data.to_pickle('data_for_training_1.pkl')

In [100]:
from sklearn.model_selection import train_test_split

train_patients, test_patients = train_test_split(np.unique(data['N']), random_state=0)
with open('dataset_description.txt', 'w') as file:
    file.writelines(f"""Total number of unique patients: {len(np.unique(data['N']))}
Patients in train: {len(train_patients)}
Patients in test: {len(test_patients)}
Total number of rows: {data.shape[0]}
Number of rows in train: {data.loc[data['N'].isin(train_patients), :].shape[0]}
Number of rows in test: {data.loc[data['N'].isin(test_patients), :].shape[0]}""")